#!/usr/bin/env python3
"""
apply_doc_theme.py — (re)apply the generated gravity doc theme to every
browser-read HTML doc, replacing whatever theme block is there now.

Supersedes `add_theme_switch.py`, and the rename records a real change of job.
The old script APPENDED a five-theme override block after each doc's existing
stylesheet. That worked once, then compounded: every doc ended up with two
`:root` blocks — ~90 lines of standard tokens shadowed by the ones below them —
and no way to ever collapse them, because "append" has no inverse. New projects
copied the scar from the templates forever.

This script REPLACES instead. The theme is now generated by
`gravity/lib/doc_theme.py` (which travels into every project via
`install_lib.py`), so the whole stylesheet can be regenerated rather than
layered over.

The one hard problem, and how it's handled
------------------------------------------
Replacing a doc's `<style>` wholesale would destroy per-doc CSS — and that CSS
is not decoration: the ARCHITECTURE pages carry 30-45 custom selectors each
(the Domain x Layer grid cells, the trace lanes, the node markers, `data-path`
anchors). Losing them silently would wreck the exact docs this is meant to
improve.

So the stylesheet is SPLIT, not overwritten:

  1. Strip the old theme block (either marker: the legacy `aurora doc theme`
     comment, or this generator's own).
  2. Split what remains into top-level rules with a brace-matching walk that
     understands comments and `@media` nesting.
  3. Drop a rule only when EVERY selector it declares is one the generator now
     defines — i.e. provably dead. Anything else is custom and is kept verbatim,
     in its original order.
  4. Emit: generated theme first, custom tail second, so custom CSS still wins.

A rule the generator doesn't define is never touched. When in doubt, this keeps.

Safety
------
`--dry-run` is the DEFAULT. Nothing is written until you pass `--apply`.
Per file it reports the line delta and how many custom rules it preserved; a
doc whose stylesheet it cannot parse is skipped and reported, never clobbered.

Usage:
    python .claude/scripts/apply_doc_theme.py                    # dry run, all docs
    python .claude/scripts/apply_doc_theme.py <project>          # dry run, one project
    python .claude/scripts/apply_doc_theme.py <project> --apply  # write
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

WORKSPACE = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(WORKSPACE / "gravity" / "lib"))
import doc_theme  # noqa: E402

# Removing the previous theme block, in two forms.
#
# NEW: an exact BEGIN…END sentinel pair. Exact removal is the whole reason the
# sentinels exist — see the note in doc_theme.css().
NEW_BLOCK_RE = re.compile(
    r"[ \t]*/\* =+ gravity:doc-theme BEGIN.*?gravity:doc-theme END =+ \*/\n?",
    re.DOTALL,
)
# LEGACY: the appended aurora block, which had no end sentinel and simply ran to
# the end of its <style> element. Anchored on `</style>` OR end-of-input, since
# this regex is applied to the contents of one <style> element, not whole file.
OLD_BLOCK_RE = re.compile(
    r"[ \t]*/\* =+ aurora doc theme.*?(?=\n[ \t]*</style>|\Z)", re.DOTALL,
)
# The per-doc banner this script writes above preserved custom CSS. It must be
# stripped before re-adding, or it compounds one copy per run.
BANNER_RE = re.compile(
    r"[ \t]*/\* =+ per-doc CSS.*?=+ \*/\n?", re.DOTALL,
)
HEAD_RE = re.compile(
    r"[ \t]*<script>/\*\s*(?:no-FOUC theme init|gravity:doc-theme: no-FOUC init)"
    r".*?</script>\n?", re.DOTALL)
BAR_RE = re.compile(r'[ \t]*<div class="themebar".*?</script>\n?', re.DOTALL)
OLD_WIDGET_RE = re.compile(r'[ \t]*<button id="theme-toggle".*?</script>\n?', re.DOTALL)
STYLE_RE = re.compile(r"(<style>)(.*?)(</style>)", re.DOTALL)


# --------------------------------------------------------------------------- #
# CSS splitting
# --------------------------------------------------------------------------- #

def _comment_mask(css: str) -> list[bool]:
    """True at every index inside a /* … */ comment, so brace scanning never
    trips on a brace that is only a character in prose."""
    mask = [False] * len(css)
    i, n = 0, len(css)
    while i < n:
        j = css.find("/*", i)
        if j < 0:
            break
        k = css.find("*/", j + 2)
        k = n if k < 0 else k + 2
        for x in range(j, k):
            mask[x] = True
        i = k
    return mask


def split_rules(css: str) -> list[tuple[str, list[str], str]]:
    """Split a stylesheet into top-level chunks.

    Returns (kind, selectors, text) where kind is 'rule' or 'at'. `text`
    includes any comments/whitespace that preceded the rule, so keeping a rule
    keeps its explanation with it.
    """
    mask = _comment_mask(css)
    out: list[tuple[str, list[str], str]] = []
    i, n, start = 0, len(css), 0
    while i < n:
        if css[i] == "{" and not mask[i]:
            sel_raw = css[start:i]
            depth, j = 1, i + 1
            while j < n and depth:
                if not mask[j]:
                    if css[j] == "{":
                        depth += 1
                    elif css[j] == "}":
                        depth -= 1
                j += 1
            text = css[start:j]
            sel_clean = re.sub(r"/\*.*?\*/", "", sel_raw, flags=re.DOTALL).strip()
            kind = "at" if sel_clean.lstrip().startswith("@") else "rule"
            if kind == "at":
                inner = css[i + 1:j - 1]
                sels = [s for _, ss, _ in split_rules(inner) for s in ss]
            else:
                sels = [s.strip() for s in sel_clean.split(",") if s.strip()]
            out.append((kind, sels, text))
            start = i = j
        else:
            i += 1
    tail = css[start:]
    if tail.strip():
        out.append(("raw", [], tail))
    return out


def generated_selectors() -> set[str]:
    """Every selector the generated theme defines — the drop list."""
    sels: set[str] = set()
    for kind, ss, _ in split_rules(doc_theme.css()):
        sels.update(ss)
    return sels


def partition(css: str, owned: set[str]) -> tuple[str, int, int]:
    """Split a doc's stylesheet into (custom_tail, kept_rules, dropped_rules).

    A rule is dropped only when every selector in it is one the generator
    defines. `@media` blocks are judged by their inner selectors.
    """
    kept: list[str] = []
    n_keep = n_drop = 0
    for kind, sels, text in split_rules(css):
        if kind == "raw":
            if text.strip() and not text.strip().startswith("/*"):
                kept.append(text)
            continue
        if sels and all(s in owned for s in sels):
            n_drop += 1
            continue
        kept.append(text)
        n_keep += 1
    return "".join(kept).strip("\n"), n_keep, n_drop


# --------------------------------------------------------------------------- #
# Rewriting one document
# --------------------------------------------------------------------------- #

def _first_real_style(src: str):
    """The first <style> ELEMENT — not a '<style>' mentioned in prose.

    Template header comments legitimately talk about the tag ("emits the
    current <style> block to paste"), and a bare STYLE_RE.search matched that
    prose first, swallowing everything up to the real stylesheet and mangling
    the page. Found by the pre-release idempotence check; comment spans are
    now excluded before matching.
    """
    comments = [(c.start(), c.end())
                for c in re.finditer(r"<!--.*?-->", src, re.DOTALL)]
    # Scan for the first non-comment `<style>` TOKEN, then anchor the element
    # match there. Iterating STYLE_RE.finditer instead is wrong twice over: a
    # rejected in-comment match still CONSUMES up to the first `</style>`, so
    # the real element either vanishes (one-style docs report "no <style>
    # block") or the search lands on element 2 (two-style docs get their
    # custom CSS block rethemed).
    i = 0
    while True:
        j = src.find("<style>", i)
        if j < 0:
            return None
        if any(a <= j < b for a, b in comments):
            i = j + 1
            continue
        return STYLE_RE.match(src, j)


def rewrite(src: str, owned: set[str]) -> tuple[str | None, dict]:
    """Return (new_source, stats). new_source is None when the doc should be
    skipped — an unparsable or non-standard doc is left exactly as it was."""
    m = _first_real_style(src)
    if not m:
        return None, {"skip": "no <style> block"}

    style = m.group(2)
    stripped = NEW_BLOCK_RE.sub("", style)
    stripped = OLD_BLOCK_RE.sub("", stripped)
    stripped = BANNER_RE.sub("", stripped)
    custom, n_keep, n_drop = partition(stripped, owned)

    new_style = "\n" + doc_theme.css()
    if custom:
        new_style += (
            "\n  /* ===== per-doc CSS — owned by THIS document, never by the "
            "generator.\n     Kept verbatim and placed last so it wins. ===== */\n"
            + custom + "\n"
        )
    out = src[:m.start(2)] + new_style + src[m.end(2):]

    # Head init: replace in place, or insert just before </head>.
    out, n_head = HEAD_RE.subn("", out)
    out = out.replace("</head>", doc_theme.head_script() + "\n</head>", 1)

    # Floating switcher: drop any prior widget, then insert before </body>.
    out = OLD_WIDGET_RE.sub("", out)
    out = BAR_RE.sub("", out)
    widget = doc_theme.themebar_html() + "\n" + doc_theme.themebar_script()
    out = out.replace("</body>", widget + "\n</body>", 1)

    return out, {"kept": n_keep, "dropped": n_drop,
                 "custom_lines": custom.count("\n") + 1 if custom else 0}


def discover(root: Path, skeleton_only: bool = False) -> list[Path]:
    """Auto-discover doc pages. Never a hardcoded list — a doc that moves into
    `.gravity/` or is added later must not be silently missed.

    `skeleton_only` restricts to the tracked gravity skeleton (the stencils plus
    the workspace's own MISSION) and touches no project repo — the mode for
    changing the protocol without mass-editing 15 independent repos in the same
    breath.
    """
    out: list[Path] = []
    seen: set[Path] = set()
    globs = [
        "gravity/templates/MISSION.template.html",
        "gravity/templates/ARCHITECTURE.template.html",
        "gravity/templates/ARCHITECTURE.domain.template.html",
        "docs/MISSION.html",
    ] if root == WORKSPACE else []
    # REPORT.template.html and the engagement report books it seeds
    # (.gravity/_roadmap/report-*.html) are deliberately NOT discovered: the
    # report is stakeholder-facing and carries its own calm standalone
    # stylesheet — not the gravity doc theme — and delivered tabs are frozen.
    for g in globs:
        p = root / g
        if p.is_file():
            out.append(p)
            seen.add(p.resolve())
    if skeleton_only:
        return out

    bases = [root] if root != WORKSPACE else sorted(
        (WORKSPACE / "repos").glob("*")) if (WORKSPACE / "repos").is_dir() else []
    for base in bases:
        if not base.is_dir():
            continue
        for pat in ("MISSION.html", "ARCHITECTURE*.html",
                    ".gravity/MISSION.html", ".gravity/ARCHITECTURE*.html",
                    ".gravity/*/ARCHITECTURE*.html", ".gravity/*/MISSION.html"):
            for p in base.glob(pat):
                # The observatory is GENERATED by its own renderer and owns its
                # own chrome; re-theming it here would fight that generator.
                if ("_observatory" in p.parts or "observatory" in p.parts
                        or "node_modules" in p.parts):
                    continue
                if p.resolve() not in seen:
                    out.append(p)
                    seen.add(p.resolve())
    return out


def main(argv=None) -> int:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except Exception:
            pass

    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[1],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("project", nargs="?",
                    help="project name/alias/path; omit for the whole workspace")
    ap.add_argument("--apply", action="store_true",
                    help="write the changes (default is a dry run)")
    ap.add_argument("--skeleton", action="store_true",
                    help="the tracked gravity skeleton only (stencils + the "
                         "workspace MISSION); touches no project repo")
    args = ap.parse_args(argv)

    if args.project:
        as_path = Path(args.project).expanduser()
        if as_path.is_dir():
            root = as_path.resolve()
        else:
            from resolve_project import resolve  # noqa: E402
            _, root = resolve(args.project)
    else:
        root = WORKSPACE

    owned = generated_selectors()
    targets = discover(root, skeleton_only=args.skeleton)
    if not targets:
        print(f"no doc pages found under {root}")
        return 0

    mode = "APPLY" if args.apply else "DRY RUN (nothing written; pass --apply)"
    print(f"gravity doc theme -> {mode}")
    print(f"  generator: gravity/lib/doc_theme.py "
          f"({len(owned)} selectors owned)\n")

    changed = skipped = 0
    for path in targets:
        src = path.read_text(encoding="utf-8")
        new, stats = rewrite(src, owned)
        rel = path.relative_to(WORKSPACE) if WORKSPACE in path.parents \
            else path
        if new is None:
            print(f"  SKIP  {rel}  ({stats['skip']})")
            skipped += 1
            continue
        if new == src:
            print(f"  same  {rel}")
            continue
        delta = new.count("\n") - src.count("\n")
        print(f"  {'write' if args.apply else 'would'} {rel}"
              f"  {delta:+d} lines  "
              f"(dropped {stats['dropped']} dead rules, "
              f"kept {stats['kept']} custom)")
        if args.apply:
            path.write_text(new, encoding="utf-8")
        changed += 1

    print(f"\n{changed} file(s) {'changed' if args.apply else 'would change'}, "
          f"{skipped} skipped, {len(targets)} scanned")
    if not args.apply and changed:
        print("re-run with --apply to write.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
